/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Cau_Thu;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trong
 */
public class ViewCauThu extends javax.swing.JFrame {
    private Cau_Thu cauThu;
    /**
     * Creates new form ViewCauThu
     */
    public ViewCauThu() {
        this.cauThu = new Cau_Thu();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLHoTen = new javax.swing.JLabel();
        jL_NamSinh = new javax.swing.JLabel();
        jLID = new javax.swing.JLabel();
        jTF_ID = new javax.swing.JTextField();
        jTF_HoTen = new javax.swing.JTextField();
        jTF_NamSinh = new javax.swing.JTextField();
        jL_ViTri = new javax.swing.JLabel();
        jCB_ViTri = new javax.swing.JComboBox<>();
        jB_Add = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();
        jB_find = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTF_TimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(910, 528));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLHoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLHoTen.setText("Ho Ten");
        jLHoTen.setToolTipText("");
        jLHoTen.setMaximumSize(new java.awt.Dimension(60, 25));
        getContentPane().add(jLHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 60, 30));

        jL_NamSinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_NamSinh.setText("Nam Sinh");
        getContentPane().add(jL_NamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 90, 30));

        jLID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLID.setText("ID");
        jLID.setMaximumSize(new java.awt.Dimension(60, 25));
        getContentPane().add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 30));

        jTF_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTF_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 180, 40));

        jTF_HoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTF_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 180, 40));

        jTF_NamSinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTF_NamSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 180, 40));

        jL_ViTri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jL_ViTri.setText("Vi Tri");
        getContentPane().add(jL_ViTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 60, 30));

        jCB_ViTri.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jCB_ViTri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thu Mon", "Hau Ve", "Tien Ve", "Tien Dao" }));
        getContentPane().add(jCB_ViTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 130, 40));

        jB_Add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jB_Add.setText("Add");
        jB_Add.setPreferredSize(new java.awt.Dimension(80, 35));
        jB_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AddActionPerformed(evt);
            }
        });
        getContentPane().add(jB_Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 90, -1));

        jB_Delete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jB_Delete.setText("Delete");
        jB_Delete.setPreferredSize(new java.awt.Dimension(80, 35));
        getContentPane().add(jB_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 90, -1));

        jB_find.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jB_find.setText("Find");
        jB_find.setMaximumSize(new java.awt.Dimension(90, 40));
        jB_find.setPreferredSize(new java.awt.Dimension(80, 35));
        jB_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_findActionPerformed(evt);
            }
        });
        getContentPane().add(jB_find, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 135, -1));
        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jTF_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(jTF_TimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 180, 35));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ho ten", "Nam Sinh", "Vi Tri"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 970, 200));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ho Ten", "Nam Sinh", "Vi tri"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setRowHeight(40);
        jTable2.setShowVerticalLines(true);
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 960, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AddActionPerformed
        try {
            Add();
        } catch (IOException ex) {
            Logger.getLogger(ViewCauThu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_AddActionPerformed

    private void jB_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_findActionPerformed
        find();
    }//GEN-LAST:event_jB_findActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DisplayClick();
    }//GEN-LAST:event_jTable1MouseClicked

    
    public void Add() throws IOException{
        this.cauThu.setId(jTF_ID.getText());
        this.cauThu.setHoTen(jTF_HoTen.getText());
        this.cauThu.setNamSinh(Integer.parseInt(jTF_NamSinh.getText()));
        this.cauThu.setViTri((String) jCB_ViTri.getSelectedItem());
        
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        
        Object[] ct = new Object[]{
            this.cauThu.getId(), 
            this.cauThu.getHoTen(), 
            String.valueOf(this.cauThu.getNamSinh()), 
            this.cauThu.getViTri()
        };
        table.addRow(ct);
        
        try (FileWriter fileWritter = new FileWriter("D:\\CauThu.dat", true); BufferedWriter bW = new BufferedWriter(fileWritter)) {
            bW.write(this.cauThu.getId() + "$" + this.cauThu.getHoTen() + "$" + this.cauThu.getNamSinh() + "$" + this.cauThu.getViTri() + "\n");
        }
    }
    
    public void DisplayClick(){
        int rowNumber = jTable1.getSelectedRow();
        System.out.println(rowNumber);
        jTF_ID.setText((String) jTable1.getValueAt(rowNumber, 0));
        jTF_HoTen.setText((String) jTable1.getValueAt(rowNumber, 1));
        jTF_NamSinh.setText(jTable1.getValueAt(rowNumber, 2) + "");
        jCB_ViTri.setSelectedItem((String) jTable1.getValueAt(rowNumber, 3));
    }
    
    public void find(){
        String search = jTF_TimKiem.getText();
        int rowNumber = jTable1.getRowCount();
        DefaultTableModel table = (DefaultTableModel) jTable2.getModel();
        table.setRowCount(0);
        for (int i = 0; i < rowNumber; i++) {
            if(search.equals(String.valueOf(jTable1.getValueAt(i, 1)))){
                this.cauThu.setId((String) jTable1.getValueAt(i, 0));
                this.cauThu.setHoTen((String) jTable1.getValueAt(i, 1));
                this.cauThu.setNamSinh(Integer.parseInt((String)jTable1.getValueAt(i, 2)));
                this.cauThu.setViTri((String) jTable1.getValueAt(i, 3));

                Object[] ct = new Object[]{
                    this.cauThu.getId(), 
                    this.cauThu.getHoTen(), 
                    String.valueOf(this.cauThu.getNamSinh()), 
                    this.cauThu.getViTri()
                };
                table.addRow(ct);
            }    
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Add;
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_find;
    private javax.swing.JComboBox<String> jCB_ViTri;
    private javax.swing.JLabel jLHoTen;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jL_NamSinh;
    private javax.swing.JLabel jL_ViTri;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTF_HoTen;
    private javax.swing.JTextField jTF_ID;
    private javax.swing.JTextField jTF_NamSinh;
    private javax.swing.JTextField jTF_TimKiem;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}
